### ISSUE TITLE
data-ng-disabled is only respected on init

### ISSUE THREAD

**Issue by yilativ** [EvanOxfeld/angular-selectize.js#9]
Great directive wrapper for Selectize! Thank you. 

Just wanted to file a bug that the wrapper doesn't update the selectize control when data-ng-disabled is used. 

Here's the plunker to demonstrate the issue. 
http://plnkr.co/edit/r4xshG5pJKZNyvYtF3C1?p=preview

**Comment by EvanOxfeld** [comment]
Thanks for reporting this issue! I agree that the wrapper should respect `ng-disabled` and `data-ng-disabled`.

I can probably get to a fix this weekend. If we can watch the `ng-disabled` or `data-ng-disabled` attribute for changes, it's just a matter of calling `enable` or `disable` on the selectize control.

**Comment by EvanOxfeld** [comment]
@yilativ I just added support for `ngDisabled` in `1.3.0`. Sorry for the delay -- turned out this was about as easy as I thought, but was too swamped at work until recently to look into it.

**Comment by yilativ** [comment]
Thank you! No worries about delays, I know how the work load can get swampy! :)

On August 1, 2014 at 2:00:10 PM, Evan Oxfeld (notifications@github.com) wrote:

@yilativ I just added support for ngDisabled in 1.3.0. Sorry for the delay -- turned out this was about as easy as I thought, but was too swamped at work until recently to look into it.
